FROM balenalib/%%BALENA_MACHINE_NAME%%

COPY ./grafana.ini /usr/share/grafana/conf/custom.ini
COPY ./grafana.db /tmp

COPY ./start.sh /usr/src/app/start.sh

RUN install_packages \
      fontconfig-config \
      fonts-dejavu-core \
      libfontconfig1 \
      ucf

RUN curl -o /tmp/grafana.deb https://dl.grafana.com/oss/release/grafana_6.1.4_armhf.deb;

RUN dpkg -i /tmp/grafana.deb && rm /tmp/grafana.deb

CMD ["/bin/sh","/usr/src/app/start.sh"]
